[package]
name = "fastlog_core"
version = "0.1.0"
edition = "2021"

[dependencies]
lz4 = "1.28.1"
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", default-features = false, features = ["clock"] }
